# server configuration
server:
  host: "http://127.0.0.1"
  port: 8081
  
# pki configuration
pki:
  rsa_bits: 2048
  serial_number: 1000
  csr_max_memory: 1024
  certificate_ttl: "8760h"
  certificate_authority: 
    common_name: "ca.scorpio.ordinarycomputing.com"
  allowed_names:
    - "^$"
    - ".*\\.scorpio\\.ordinarycomputing\\.com"
oauth:
  enabled: False
  trusted_issuers:
    - "http://scorpio.ordinarycomputing.com:8082/jwks"