# server configuration
server:
  host: "http://127.0.0.1"
  port: 8081
# pki configuration
pki:
  rsa_bits: 2048
  serial_number: 1000
  csr_max_memory: 1024
  certificate_ttl: "60m"
  certificate_authority: 
    - "scorpio.io"
    - "*.scorpio.io"
  allowed_sans:
    - ".*\\.example\\.com"