basePath: /
host: localhost:8081
info:
  contact: {}
  description: A configurable X509 Certificate Authority management tool implemented
    in Go.
  license:
    name: MIT
    url: https://mit-license.org
  title: Scorpio PKI Service
  version: "1.0"
paths:
  /certificate:
    post:
      consumes:
      - multipart/form-data
      description: The CSR handler is responsible for processing Certificate Signing
        Requests (CSRs). It validates incoming CSR data, ensuring compliance with
        formatting and policy standardsnn are met. Once validated, the handler creates
        a new digital certificate with the entity's public key and associated identity
        information. The handler produces and returns a PEM encoded certificate
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: csr post form field is blank
          schema:
            type: string
      summary: Processes Certificate Signing Requests and returns X.509
      tags:
      - csr
  /p12:
    post:
      consumes:
      - multipart/form-data
      description: CSRHandler accepts a CSR in a multipart form data request and returns
        a PEM file or JSON content given HTTP Accept header
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: pkcs post form field is blank
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: 'Handles PKCS #12 request and PKCS #12'
      tags:
      - pkcs-12
  /public:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Exposes the CAs Public Key
      tags:
      - public
      - rsa
swagger: "2.0"
